import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Providers from "./Providers";
import TopNav from "./_components/TopNav";
import StateProvider from "./StateProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TRADE",
  description: "Generated by ARNNVV",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateProvider>
          <Providers>
            <TopNav />
            {children}
          </Providers>
        </StateProvider>
      </body>
    </html>
  );
}
